// -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by:
//        The WPF ShaderEffect Generator
//        http://wpfshadergenerator.codeplex.com
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace HscLib.ShaderEffects
{
    using System;
    using System.Windows;
    using System.Windows.Media;
    using System.Windows.Media.Effects;
    using System.Windows.Media.Media3D;
    
    
    /// <summary></summary>
    public class Saturation : System.Windows.Media.Effects.ShaderEffect
    {
        
        /// <summary>The brightness offset.</summary>
        public static readonly DependencyProperty SaturationValueProperty = DependencyProperty.Register("SaturationValue", typeof(System.Double), typeof(Saturation), new PropertyMetadata((double)0, PixelShaderConstantCallback(0)));
        /// <summary>The implicit input sampler passed into the pixel shader by WPF.</summary>
        public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(Saturation), 0, SamplingMode.Auto);
        
        public Saturation()
        {
            PixelShader pixelShader = new PixelShader();
            pixelShader.UriSource = new Uri("/HyperSearch;component/ShaderEffects/Saturation.ps", UriKind.Relative);
            this.PixelShader = pixelShader;
            this.UpdateShaderValue(SaturationValueProperty);
            this.UpdateShaderValue(InputProperty);
            this.DdxUvDdyUvRegisterIndex = -1;
        }
        
        /// <summary>The brightness offset.</summary>
        public virtual double SaturationValue
        {
            get
            {
                return ((double)(this.GetValue(SaturationValueProperty)));
            }
            set
            {
                this.SetValue(SaturationValueProperty, value);
            }
        }
        
        /// <summary>The implicit input sampler passed into the pixel shader by WPF.</summary>
        public virtual System.Windows.Media.Brush Input
        {
            get
            {
                return ((System.Windows.Media.Brush)(this.GetValue(InputProperty)));
            }
            set
            {
                this.SetValue(InputProperty, value);
            }
        }
    }
}
